### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by qhq123** [uds-lsv/TOKEN-is-a-MASK#1]
hello！I am very interested in your work，and may I know when the code will be uploaded？THANKS!

**Comment by dklakow** [comment]
Thanks for your interest. David will take care of that
Best,
Dietrich

Am 19.07.22 um 05:52 schrieb qhq123:

**Comment by qhq123** [comment]
can you release the code for few-shot experiment? thank you！

**Comment by dadelani** [comment]
Sorry for the delay. The zero-shot and few-shot examples based on CoNLL03 are available. Please, check the readme.

**Comment by qhq123** [comment]
Thanks for the reply! Wish scientific research success, all the best!

**Comment by dadelani** [comment]
Thanks
